from pydantic import BaseModel, Field
from typing import List, Optional, Dict


class QueryState(BaseModel):
    """Tracks the user's query and its semantic routing."""
    original_query: str = Field(description="The exact raw input from the user.")
    route: Optional[str] = Field(
        default=None,
        description="Target route: 'content', 'bibliometric', 'trend', or 'current_world'."
    )
    reformulated_query: Optional[str] = Field(
        default=None,
        description="The LLM-rewritten query optimized for technical retrieval."
    )


class MemoryState(BaseModel):
    """Holds all retrieved evidence from internal and external sources."""
    serialized_graph_triples: List[str] = Field(
        default_factory=list,
        description="Natural language sentences serialized from Neo4j topology."
    )
    vector_chunks: List[str] = Field(
        default_factory=list,
        description="Raw text chunks retrieved via FAISS."
    )
    lexical_chunks: List[str] = Field(
        default_factory=list,
        description="Raw text chunks retrieved via Disk-Backed BM25."
    )
    external_api_abstracts: List[str] = Field(
        default_factory=list,
        description="Vetted abstracts from Crossref, OpenAlex, and Semantic Scholar."
    )


class EvaluationState(BaseModel):
    """Tracks the 100-Point Evidence Sufficiency Rubric and agentic retry constraints."""
    rubric_score: int = Field(default=0, ge=0, le=100, description="Total evidence score.")
    retrieval_confidence: int = Field(default=0, le=40)
    answer_specificity: int = Field(default=0, le=25)
    source_diversity: int = Field(default=0, le=15)
    metadata_completeness: int = Field(default=0, le=10)
    recency: int = Field(default=0, le=10)

    is_evidence_weak: bool = Field(
        default=True,
        description="True if rubric_score < 80. Triggers external search."
    )
    drift_guard_overlap_pct: float = Field(
        default=0.0,
        description="Must be >= 0.30 during agentic retry to prevent semantic drift."
    )


class CompressionState(BaseModel):
    """Manages the AttentionRAG micro-window pruning."""
    focal_token: Optional[str] = Field(
        default=None,
        description="The target token generated by the answer hint prefix."
    )
    micro_windows: List[str] = Field(
        default_factory=list,
        description="3,500-char chunks split into 50-300 token segments."
    )
    compression_ratio: float = Field(default=0.0)
    final_pruned_prompt: str = Field(
        default="",
        description="The high-density context passed to the Generator."
    )


class GenerationState(BaseModel):
    """Handles the final answer and the self-correction loop."""
    draft_answer: str = Field(default="")
    critic_feedback: Optional[str] = Field(
        default=None,
        description="Feedback from the Step 11 Quality Check."
    )
    retry_count: int = Field(
        default=0,
        le=1,
        description="Enforces the single automatic regeneration limit."
    )


class AletheiaState(BaseModel):
    """
    The master state object passed between all LangGraph nodes.
    """
    query: QueryState
    memory: MemoryState
    evaluation: EvaluationState
    compression: CompressionState
    generation: GenerationState

    pipeline_cost: float = Field(
        default=0.0,
        description="Running total of LLM API costs."
    )